version: "3"

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: database
      POSTGRES_PASSWORD: database
    ports:
      - "5432:5432"


  frontend:
    build:
      context: ./frontend

    command: npm start
    volumes:
      - ./frontend:/app/frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
      
  backend:
    image: python:3.9
    build:
      context: ./backend
    volumes:
      - ./backend:/app/backend
    ports:
      - "8000:8000"
    depends_on:
      - postgres