"""Added text field to Chat

Revision ID: 0324bbb518a6
Revises: 56e1f3397991
Create Date: 2024-01-07 22:22:08.253922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0324bbb518a6'
down_revision: Union[str, None] = '56e1f3397991'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat', sa.Column('text', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat', 'text')
    # ### end Alembic commands ###
