"""Updated user with google_id field

Revision ID: d07bc6e48c8c
Revises: 0324bbb518a6
Create Date: 2024-01-12 00:38:34.474573

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd07bc6e48c8c'
down_revision: Union[str, None] = '0324bbb518a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('google_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'google_id')
    # ### end Alembic commands ###
